apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosir-portal
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-dns
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - app.e-mosir.pl
      secretName: mosir-portal-tls
  rules:
    - host: app.e-mosir.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mosir-portal
                port:
                  number: 80
