apiVersion: v1
kind: Service
metadata:
  name: mosir-portal
  namespace: apps
  labels:
    app: mosir-portal
spec:
  selector:
    app: mosir-portal
  ports:
    - name: http
      port: 80
      targetPort: http
